image:
  repository: nginx
  tag: 1.28.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  host: foo.com
  controller: "nginx"

configMap:
  name: "nginxConfig"
  nginxConf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 'HELLO WORLD';
        }
      }
    }

namespace: nginx
replicaCount: 1